version: '3'

services:
  ocrllm-api:
    build: .
    image: yixing/ocrllm-api
    container_name: ocrllm-api
    network_mode: host
    restart: on-failure:5
    volumes:
      - ./temp:/code/temp
      - ./conf:/code/conf
      - ./assets:/code/assets
      - ./db:/code/db
    environment:
      - CONFIG_FILE=conf/config-prod.yaml